# Generated by Django 4.2 on 2023-04-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SamaajMemberMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=256, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=256, verbose_name="Father / Husband Name"
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=256, verbose_name="Mothers Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=256, verbose_name="Last Name"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SamaajMemberMosaadMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Mosaad Name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "samaaj_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_entry.samaajmembermaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SamaajMemberMobileNumberMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=10, verbose_name="Mobile Number"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "samaaj_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_entry.samaajmembermaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SamaajMemberEmailAddressMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_id",
                    models.EmailField(max_length=256, verbose_name="Email Address"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "samaaj_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_entry.samaajmembermaster",
                    ),
                ),
            ],
        ),
    ]
